#!/bin/bash

#$ -S /bin/bash

#$ -wd /home/bgaujac/diswae

#$ -l gpu=True
#$ -l tmem=5G
#$ -l h_rt=24:00:00

#$ -t 64-81

#$ -N disWAE_celebA

source /share/apps/examples/source_files/python/python-3.6.4.source
source /share/apps/examples/source_files/cuda/cuda-9.0.source

# python3 run.py --out_dir dsprites  --exp dsprites --enum 100 --lmba0 1 --lmba1 1
python3 run_array_celebA.py --num_it 300000 --idx $SGE_TASK_ID --exp celebA --out_dir celebA --sigma_pen True --model TCWAE
