#!/bin/bash

#$ -S /bin/bash

#$ -wd /home/gaujac/diswae

#$ -l gpu=true
#$ -l tmem=8G
#$ -l h_rt=15:00:00

#$ -t 1-108

#$ -N l2mwsScrdsprites

source /share/apps/examples/source_files/python/python-3.6.4.source
source /share/apps/examples/source_files/cuda/cuda-9.0.source

python3 run_array.py --num_it 300000 --id $SGE_TASK_ID --dataset screamdsprites --save_data --save_model --out_dir ScrdSprites_l2sq --model TCWAE_MWS --cost l2sq
