#!/bin/bash

#$ -S /bin/bash

#$ -wd /home/bgaujac/diswae

#$ -l gpu=True
#$ -l tmem=24G
#$ -l h_rt=8:00:00

#$ -t 1-7

#$ -N gancelebA

source /share/apps/examples/source_files/python/python-3.6.4.source
source /share/apps/examples/source_files/cuda/cuda-10.0.source

python3 run_array.py --num_it 600000 --id $SGE_TASK_ID --dataset celebA --cost l2sq --save_data --save_model --out_dir celebA_batchnorm --model TCWAE_MWS
